project_id: 5
api_token_env: CROWDIN_PERSONAL_TOKEN
base_url: https://unraid.api.crowdin.com
preserve_hierarchy: true
files:
  # JSON translation files
  - source: /i18n/en/**/*
    translation: /i18n/%two_letters_code%/**/%original_file_name%
  # Docs Markdown files
  - source: /docs/**/*
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/**/%original_file_name%
    content_segmentation: 0
    escape_quotes: 0
    escape_special_characters: 0
    excluded_strings:
      - ":::note"
      - ":::tip"
      - ":::info"
      - ":::caution"
      - ":::danger"
      - ":::important"
      - ":::warning"
      - ":::"
