project_id: 5
api_token_env: CROWDIN_PERSONAL_TOKEN
base_url: https://unraid.api.crowdin.com
preserve_hierarchy: true
files:
  # JSON translation files
  - source: /i18n/en/**/*
    translation: /i18n/%two_letters_code%/**/%original_file_name%
  # Docs Markdown files
  - source: /docs/**/*.md
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/**/%original_file_name%
    type: mdx_v2
  # Docs MDX files
  - source: /docs/**/*.mdx
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/**/%original_file_name%
    type: mdx_v2
  # JSON files in docs
  - source: /docs/**/*.json
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/**/%original_file_name%
    update_option: update_without_changes
  # PNG images in docs
  - source: /docs/**/*.png
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/**/%original_file_name%
    update_option: update_without_changes
